// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Streaming.Pokemon
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class From : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"From\",\"namespace\":\"Streaming.Pokemon\",\"fields\":[{\"name\":" +
				"\"Lat\",\"type\":\"string\"},{\"name\":\"Long\",\"type\":\"string\"}]}");
		private string _Lat;
		private string _Long;
		public virtual Schema Schema
		{
			get
			{
				return From._SCHEMA;
			}
		}
		public string Lat
		{
			get
			{
				return this._Lat;
			}
			set
			{
				this._Lat = value;
			}
		}
		public string Long
		{
			get
			{
				return this._Long;
			}
			set
			{
				this._Long = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Lat;
			case 1: return this.Long;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Lat = (System.String)fieldValue; break;
			case 1: this.Long = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
