// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Streaming.Pokemon
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Walk : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""Walk"",""namespace"":""Streaming.Pokemon"",""fields"":[{""name"":""From"",""type"":{""type"":""record"",""name"":""From"",""namespace"":""Streaming.Pokemon"",""fields"":[{""name"":""Lat"",""type"":""string""},{""name"":""Long"",""type"":""string""}]}},{""name"":""To"",""type"":{""type"":""record"",""name"":""To"",""namespace"":""Streaming.Pokemon"",""fields"":[{""name"":""Lat"",""type"":""string""},{""name"":""Long"",""type"":""string""}]}},{""name"":""Distance"",""type"":""int""}]}");
		private Streaming.Pokemon.From _From;
		private Streaming.Pokemon.To _To;
		private int _Distance;
		public virtual Schema Schema
		{
			get
			{
				return Walk._SCHEMA;
			}
		}
		public Streaming.Pokemon.From From
		{
			get
			{
				return this._From;
			}
			set
			{
				this._From = value;
			}
		}
		public Streaming.Pokemon.To To
		{
			get
			{
				return this._To;
			}
			set
			{
				this._To = value;
			}
		}
		public int Distance
		{
			get
			{
				return this._Distance;
			}
			set
			{
				this._Distance = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.From;
			case 1: return this.To;
			case 2: return this.Distance;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.From = (Streaming.Pokemon.From)fieldValue; break;
			case 1: this.To = (Streaming.Pokemon.To)fieldValue; break;
			case 2: this.Distance = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
