// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace io.confluent.developer.avro
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class TicketSale : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"TicketSale\",\"namespace\":\"io.confluent.developer.avro\",\"f" +
				"ields\":[{\"name\":\"title\",\"type\":\"string\"},{\"name\":\"sale_ts\",\"type\":\"string\"},{\"na" +
				"me\":\"ticket_total_value\",\"type\":\"int\"}]}");
		private string _title;
		private string _sale_ts;
		private int _ticket_total_value;
		public virtual Schema Schema
		{
			get
			{
				return TicketSale._SCHEMA;
			}
		}
		public string title
		{
			get
			{
				return this._title;
			}
			set
			{
				this._title = value;
			}
		}
		public string sale_ts
		{
			get
			{
				return this._sale_ts;
			}
			set
			{
				this._sale_ts = value;
			}
		}
		public int ticket_total_value
		{
			get
			{
				return this._ticket_total_value;
			}
			set
			{
				this._ticket_total_value = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.title;
			case 1: return this.sale_ts;
			case 2: return this.ticket_total_value;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.title = (System.String)fieldValue; break;
			case 1: this.sale_ts = (System.String)fieldValue; break;
			case 2: this.ticket_total_value = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
