// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Streaming.Pokemon
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	/// <summary>
	/// Schema para telemetria da demo do kafka, em um simnples jogo
	/// </summary>
	public partial class PlayerAction : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""PlayerAction"",""namespace"":""Streaming.Pokemon"",""fields"":[{""name"":""Timestamp"",""type"":""long""},{""name"":""Player"",""type"":{""type"":""record"",""name"":""Player"",""namespace"":""Streaming.Pokemon"",""fields"":[{""name"":""PlayerID"",""type"":""string""},{""name"":""PlayerName"",""type"":""string""}]}},{""name"":""Walk"",""type"":{""type"":""record"",""name"":""Walk"",""namespace"":""Streaming.Pokemon"",""fields"":[{""name"":""From"",""type"":{""type"":""record"",""name"":""From"",""namespace"":""Streaming.Pokemon"",""fields"":[{""name"":""Lat"",""type"":""string""},{""name"":""Long"",""type"":""string""}]}},{""name"":""To"",""type"":{""type"":""record"",""name"":""To"",""namespace"":""Streaming.Pokemon"",""fields"":[{""name"":""Lat"",""type"":""string""},{""name"":""Long"",""type"":""string""}]}},{""name"":""Distance"",""type"":""int""}]}},{""name"":""Score"",""type"":{""type"":""record"",""name"":""Score"",""namespace"":""Streaming.Pokemon"",""fields"":[{""name"":""ScoredPoints"",""type"":""int""}]}}]}");
		private long _Timestamp;
		private Streaming.Pokemon.Player _Player;
		private Streaming.Pokemon.Walk _Walk;
		private Streaming.Pokemon.Score _Score;
		public virtual Schema Schema
		{
			get
			{
				return PlayerAction._SCHEMA;
			}
		}
		public long Timestamp
		{
			get
			{
				return this._Timestamp;
			}
			set
			{
				this._Timestamp = value;
			}
		}
		public Streaming.Pokemon.Player Player
		{
			get
			{
				return this._Player;
			}
			set
			{
				this._Player = value;
			}
		}
		public Streaming.Pokemon.Walk Walk
		{
			get
			{
				return this._Walk;
			}
			set
			{
				this._Walk = value;
			}
		}
		public Streaming.Pokemon.Score Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				this._Score = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Timestamp;
			case 1: return this.Player;
			case 2: return this.Walk;
			case 3: return this.Score;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Timestamp = (System.Int64)fieldValue; break;
			case 1: this.Player = (Streaming.Pokemon.Player)fieldValue; break;
			case 2: this.Walk = (Streaming.Pokemon.Walk)fieldValue; break;
			case 3: this.Score = (Streaming.Pokemon.Score)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
