// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Streaming.Pokemon
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class Player : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"Player\",\"namespace\":\"Streaming.Pokemon\",\"fields\":[{\"name" +
				"\":\"PlayerID\",\"type\":\"string\"},{\"name\":\"PlayerName\",\"type\":\"string\"}]}");
		private string _PlayerID;
		private string _PlayerName;
		public virtual Schema Schema
		{
			get
			{
				return Player._SCHEMA;
			}
		}
		public string PlayerID
		{
			get
			{
				return this._PlayerID;
			}
			set
			{
				this._PlayerID = value;
			}
		}
		public string PlayerName
		{
			get
			{
				return this._PlayerName;
			}
			set
			{
				this._PlayerName = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.PlayerID;
			case 1: return this.PlayerName;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.PlayerID = (System.String)fieldValue; break;
			case 1: this.PlayerName = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
